version: '{build}'
configuration:
- MINGW_64
- MINGW_32
install: []
build_script:
- call .ci\build.bat
cache:
- .deps\usr -> third-party\CMakeLists.txt
artifacts:
- path: build/Neovim.zip
- path: build/Neovim.exe
